apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: happyticket
type: Opaque
stringData:
  # Database credentials
  ConnectionStrings__DefaultConnection: "database credentials here"
  SQL_SA_PASSWORD: "StrongPasswordHere"

  # JWT secret
  JwtSettings__Key: "CHANGE_ME_JWT_KEY"

  # Email password
  EmailConfig__Password: "CHANGE_ME_EMAIL_PASSWORD"

  # Telr sensitive
  Telr__AuthKey: "CHANGE_ME_TELR_AUTH"
  Telr__SecretKey: "CHANGE_ME_TELR_SECRET"

  # Encryption keys
  EncryptionKeys__LongIdEncryptionKey: "CHANGE_ME_ENCRYPTION_KEY"

  # FCM sensitive private key
  FCM__PRIVATEKEY: "CHANGE_ME_FCM_KEY"
  # MinIO sensitive
  MinIO__AccessKey: "CHANGE_ME_MINIO_ACCESS"
  MinIO__SecretKey: "CHANGE_ME_MINIO_SECRET"
