apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: happyticket
type: Opaque
stringData:
  ConnectionStrings__Sql: Server=mssql,1433;Database=NewHappy2;User Id=sa;Password=Anas@8264;TrustServerCertificate=True;
  JwtSettings__Key: RlYI92Na7vlEKkrl7Wu6TA8HjE9eWfWGFKr2kNm3r1mwdSCbsq0VynyTpS0bBoLS+50R+dKhdqi7RiW8=
  EmailConfig__Password: Aa@1243568790
  Telr__AuthKey: ZjjnQ^4368~WL2H8
  Telr__SecretKey: jRRXEOQXRo
  EncryptionKeys__LongIdEncryptionKey: S9UX2uqzRJVxSSi7ZbyDvVZgcBw8CuVa
  SQL_SA_PASSWORD: Anas@8264
