apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: happyticket
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: api
      containers:
        - name: api
          image: ammarabdelhady8132/happyticket-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          volumeMounts:
            - name: wwwroot-volume
              mountPath: /app/wwwroot
            - name: appsettings-volume
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
            - name: dataprotection-volume
              mountPath: /app/dataprotection
      volumes:
        - name: wwwroot-volume
          persistentVolumeClaim:
            claimName: wwwroot-pvc
        - name: appsettings-volume
          configMap:
            name: api-appsettings-json
        - name: dataprotection-volume
          persistentVolumeClaim:
            claimName: dataprotection-pvc
