apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: happyticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ammarabdelhady8132/happyticket-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: wwwroot-volume
              mountPath: /app/wwwroot
      volumes:
        - name: wwwroot-volume
          persistentVolumeClaim:
            claimName: wwwroot-pvc
