apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: happyticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - controlplane
                      - worker-1
      containers:
        - name: api
          image: ammarabdelhady8132/happyticket-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          volumeMounts:
            - name: wwwroot-volume
              mountPath: /app/wwwroot
            - name: appsettings-volume
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
      volumes:
        - name: wwwroot-volume
          persistentVolumeClaim:
            claimName: wwwroot-pvc
        - name: appsettings-volume
          configMap:
            name: api-appsettings-json
