apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: happyticket
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 5000
    
      targetPort: 5000
      nodePort: 32123
