apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv-worker-1
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-expandable
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data/mssql-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1
