# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mssql-pv
#   namespace: happyticket
# spec:
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /opt/happyticket/mssql
