apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-nfs-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 142.132.210.239
    path: /mnt/nfs-shared/mssql
