apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  namespace: happyticket
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  storageClassName: nfs
