apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-nfs-pvc
  namespace: happyticket
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
