# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mssql-mssql-0
#   namespace: happyticket
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: manual
