apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: happyticket
spec:
  serviceName: db
  replicas: 1  
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
              name: tcp
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: db-storage
              mountPath: /var/opt/mssql
            - name: backup-nfs              
              mountPath: /backups
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: mssql-nfs-pvc
        - name: backup-nfs                   
          nfs:
            server: 142.132.210.239
            path: /exports/mssql-backups
