apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: happyticket
spec:
  serviceName: "mssql"
  replicas: 2
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: []
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - controlplane
                      - worker-1
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
            - name: mssql
              mountPath: /var/opt/mssql
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: MSSQL_SA_PASSWORD
          resources:
            requests:
              memory: "6Gi"
              cpu: "3"
            limits:
              memory: "10Gi"
              cpu: "4"
          volumeMounts:
            - name: mssql
              mountPath: /var/opt/mssql
      securityContext:
        fsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-expandable
        resources:
          requests:
            storage: 60Gi
