apiVersion: v1
kind: Service
metadata:
  name: db-nodeport
  namespace: happyticket
spec:
  type: NodePort
  ports:
    - port: 1433       
      targetPort: 1433 
      nodePort: 31433 
  selector:
    statefulset.kubernetes.io/pod-name: db-0
