apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-backup-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/happyticket/mssql-backups