apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataprotection-pvc
  namespace: happyticket
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
