apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataprotection-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /exports/dataprotection
    server: 188.138.101.4
