apiVersion: v1
kind: Service
metadata:
  name: sqlpad
  namespace: happyticket
spec:
  type: NodePort
  selector:
    app: sqlpad
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000