apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlpad
  namespace: happyticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlpad
  template:
    metadata:
      labels:
        app: sqlpad
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-1
      containers:
        - name: sqlpad
          image: ammarabdelhady8132/sqlpad-mssql:latest
          ports:
            - containerPort: 3000
          env:
            - name: SQLPAD_PORT
              value: "3000"
            - name: SQLPAD_ADMIN
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: SQLPAD_ADMIN
            - name: SQLPAD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: SQLPAD_ADMIN_PASSWORD
            - name: SQLPAD_APP_LOG_LEVEL
              value: "debug"
            - name: SQLPAD_CONNECTIONS__default__name
              value: "HappyTicket-MSSQL"
            - name: SQLPAD_CONNECTIONS__default__driver
              value: "sqlserver"
            - name: SQLPAD_CONNECTIONS__default__database
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: DB_NAME
            - name: SQLPAD_CONNECTIONS__default__username
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: DB_USER
            - name: SQLPAD_CONNECTIONS__default__password
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: DB_PASSWORD
            - name: SQLPAD_CONNECTIONS__default__host
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: DB_HOST
            - name: SQLPAD_CONNECTIONS__default__port
              valueFrom:
                secretKeyRef:
                  name: sqlpad-db-secret
                  key: DB_PORT
          volumeMounts:
            - name: sqlpad-data
              mountPath: /var/lib/sqlpad
      volumes:
        - name: sqlpad-data
          emptyDir: {}